### ISSUE TITLE
https and mp3

### ISSUE THREAD

**Issue by nebulos13** [ohmic-net/pico_dsp#2]
hello i try webradio in arduino -internet-radio.ino with this list radio:

https://radiobonheur.ice.infomaniak.ch/radiobonheur-128-1.mp3
http://direct.franceinter.fr/live/franceinter-midfi.mp3
https://ais-live.cloud-services.paris:8443/rfm.mp3
http://cdn.nrjaudio.fm/audio1/fr/30401/mp3_128.mp3?origine=fluxradios
http://radioclassique.ice.infomaniak.ch/radioclassique-high.mp3
http://radio8.pro-fhi.net:9005/atlantis320
http://tachyon.shoutca.st:8084/live
http://stream.levillage.org/canalb?1362308951917.mp3

but nothing playing just http://direct.franceinter.fr/live/franceinter-midfi.mp3
how to have mp3 extention and https
thanks to your answer

**Comment by nebulos13** [comment]
now my problem is the button to change mp3 flux

**Comment by g0fcu** [comment]
There is a difference in code between the Arduino IDE and VSCode IDE versions. The Arduino version has the set up of the interrupt which triggers when the button is pressed. However, for me this version continuously reboots. The VSCode has these lines (123-127) commented out so the station which plays is that which station_select is set to in Setup(). Uncommenting these lines causes the same constant reboots as in the Arduino version.

**Comment by nebulos13** [comment]
Thanks to your answer. Have you solution to use button to change radio station ?

**Comment by g0fcu** [comment]
I just cloned the git repository again and my previous comment about code differences is wrong (I must have made the change). The button and the interrupt task is not initialised as the code is commented out, un-commenting it causes the device to continuously reboot. I don't know why.

**Comment by nebulos13** [comment]
voici le modèle 3D du boitier , here is the 3D model of the box:: [https://www.nebulose.fr/modele3d.zip](url)

pour le bouton c'est quoi le code pour changer de radio?
for the button what is the code to change the radio?

**Comment by andy-wi** [comment]
@nebulos13 @g0fcu the button and RTC variable code was originally written in an earlier framework, if you are using VSCode, you can change the configuration in the platformio.ini file to; 

`platform = espressif32@3.0.0`

And it will run okay and change stations on the button press. Something changed after one of the subsequent updates after version 3.0.0 and the code needs to be debugged and updated for later platform versions. I'll push a commit now to the repository with the above change and leave this issue open for the time being.

**Comment by nebulos13** [comment]
thanks but i use arduino IDE : /main/puca_dsp-arduino/Original%20Edition/arduino-internet_radio)/arduino-internet_radio.ino

**Comment by nebulos13** [comment]
Hello in visual studio code i have this error when i build projet webradio: pio\build\tinypico\lib103\STM32duino_STM32Ethernet\EthernetServer.cpp.o] Error 1

**Comment by andy-wi** [comment]
hi @nebulos13 I'm not sure you have the correct toolchain set up for your project.... the STM32duino libraries are not required for this project and EthernetServer.cpp is not a dependency of this example. Did you install PlatformIO and ESP-IDF as extensions in VS code and could you post your platform.ini file?

**Comment by andy-wi** [comment]
When your build starts in VS Code, what platform and packages are installed, e.g;  

```
PLATFORM: Espressif 32 (3.0.0) > TinyPICO
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.10004.210126 (1.0.4) 
 - tool-esptoolpy @ 1.30000.201119 (3.0.0) 
 - toolchain-xtensa32 @ 2.50200.97 (5.2.0) 
```

**Comment by nebulos13** [comment]
it's ok with the button  !

platformio.ini
-->
[env:tinypico]
platform = espressif32@3.0.0
board = tinypico
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.f_cpu = 240000000L
board_build.flash_size = 4MB
board_build.partitions = min_spiffs.csv
board_build.flash_mode = dio
; Serial Monitor options
monitor_speed = 115200

upload_port = COM3
build_type = release
build_flags =
    ;-DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
    ;-DBOARD_HAS_PSRAM
    ;-mfix-esp32-psram-cache-issue
    ;-DCORE_DEBUG_LEVEL=5 




and

add  //conf.clk_flags = 0; ligne in WM8978.cpp ligne 57

**Comment by nebulos13** [comment]
thanks

**Comment by nebulos13** [comment]
;-)
