### ISSUE TITLE
Not an issue: Puca DSP support added to WLED-MoonModules!

### ISSUE THREAD

**Issue by troyhacks** [ohmic-net/pico_dsp#7]
WM8978 support for WLED AudioReactive has been on my to-do list for well over a year - and getting a few Puca DSP boards yesterday pushed me to finally do it:

https://github.com/MoonModules/WLED/pull/84

This should be merged in shortly, and I would expect it'll be accepted up to WLED "mainstream" in due time. 

Currently it's set to do line-in with loopback/passthru to line-out, but I may eventually create a separate config for microphone input. I'm mostly working on line-in for audio reactive work as microphones aren't the ideal solution for accuracy in loud environments like DJ events, live performances, etc.

This is a great board, thanks for developing it! A huge improvement over the LyraT I've been targeting (and also added to WLED!)
 
 My working tree is here if anyone wants to try it sooner: https://github.com/troyhacks/WLED/tree/WM8978

**Comment by andy-wi** [comment]
Thanks @troyhacks for adding the WM8978 support to WLED AudioReactive! 

And also for the feedback on the PUCA DSP board, there are no documented hardware issues with it as far as I'm aware and it was fully tested during development, if you come across anything though please open an issue here as may be useful for other developers.
