### ISSUE TITLE
Question rather than issue: Is there some JTAG documentation somewhere?

### ISSUE THREAD

**Issue by AndrewCapon** [ohmic-net/pico_dsp#9]
Hi Guys,

I want to use the USB port as a midi device so I need to get JTAG debugging going over the pins.

Is there any documentation anyway about how to do this, pins to use, fuses to burn etc?

Many thanks

Andy

**Comment by AndrewCapon** [comment]
Actually is it even possible to use the USB at all or is it just power and the serial port?

**Comment by andy-wi** [comment]
This issue was answered in email conversation at the time of posting. Just adding here as well;

Yes the JTAG pins are available; see the ESP32-PICO-D4 datasheet for details on JTAG debugging.  

The USB is just power/charging and serial communication (as per schematics).
